export {
  aiChat,
  aiExplicar,
  aiResumo as gerarResumo,
  aiGerarQuestoes,
  aiExplicarAlternativa,
  aiCorrigirRedacao,
  aiAnaliseDesempenho,
  aiRecomendacoes,
  aiGerarTemaRedacao as gerarTemaRedacao,
  aiGerarPlano as gerarPlanoAI,
  type ChatMessage,
  type QuestaoGerada,
  type CorrecaoRedacao,
  type AnaliseDesempenho,
  type PlanoAIInput,
} from "./ai.service";
